apiVersion: v1
kind: Secret
metadata:
  name: fennel-chain-secrets
type: Opaque
stringData:
  # Replace with actual value from your docker-compose
  chainsuri: "lounge kidney debate morning hood melt sibling ghost horse veteran stock wet"
---
apiVersion: v1
kind: Secret
metadata:
  name: fennel-peer-secrets
type: Opaque
stringData:
  # Replace with actual value from your docker-compose
  peer1suri: "theory elite silent donor siren puzzle salad calm uncle eyebrow gather ostrich"
  peer2suri: "wash project announce toe dune buffalo come rate mystery grunt put art"
---
apiVersion: v1
kind: Secret
metadata:
  name: fennel-node-keys
type: Opaque
# This will be populated by the polkadot-node-key-configurator from polkadot-k8s
# or can be manually created after generating appropriate node keys
stringData:
  chain-node-key: ""
  peer-node-key: ""
  peer2-node-key: "" 