# Chain Node deployment values
image:
  repository: ghcr.io/fennellabs/fennel-solonet
  tag: latest  # Replace with appropriate tag

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 2000m
    memory: 4Gi

# Chain-specific configuration
nodeKey:
  # Will generate a random node key if not provided
  type: random

# Chain identity configuration
extraLabels:
  node-role: validator
  chain-role: authority

# Runtime arguments
extraArgs:
  - "--chain=/fennel/fennelSpecRaw.json"
  - "--validator"
  - "--name=chain-node"
  - "--port=30333"
  - "--rpc-port=9944"
  - "--prometheus-port=9615"

# Substrate-specific configuration
substrate:
  enabled: true
  chain: "fennel"
  chainType: "live"

# Persistence configuration
persistence:
  enabled: true
  size: "100Gi"
  mountPath: "/data"

# Secret containing validator keys
secretEnv:
  enabled: true
  keys:
    - name: SEED_PHRASE
      valueFrom:
        secretKeyRef:
          name: fennel-chain-secrets
          key: chainsuri

# Service configuration
service:
  # Use NodePort as per your original configuration
  type: NodePort
  ports:
    - name: p2p
      port: 30333
      targetPort: 30333
      nodePort: 30333
    - name: rpc
      port: 9944
      targetPort: 9944
      nodePort: 9944 