apiVersion: v1
kind: Secret
metadata:
  name: bootnode-static-keys
  namespace: fennel
  labels:
    app.kubernetes.io/name: fennel-bootnodes
    app.kubernetes.io/component: discovery
type: Opaque
data:
  # boot0.key - Static network key for bootnode-0 (base64 encoded)
  # Generate with: subkey generate-node-key --file boot0.key && base64 -w 0 boot0.key
  boot0.key: ZTFmMWE0Nzc5Yzc1NTJhNDNjYTMzNDFhNWUzNDM1YzMwOGU2YTkwYjhkYjc5OTNmMmMxODBiYjkxOThhNzhkMgo=  # PLACEHOLDER - Will be populated during deployment
  
  # boot1.key - Static network key for bootnode-1 (base64 encoded)  
  # Generate with: subkey generate-node-key --file boot1.key && base64 -w 0 boot1.key
  boot1.key: NzViNjU0MmExNDk4ZjRlNzUxYzYxZWViNTMzNmQ4ZjQ0YjIxODhlN2E1NDQ5ZDA2OTVkYTU2MmM0NWVjNTljNwo=  # PLACEHOLDER - Will be populated during deployment

---
# Script to generate and populate the keys
# Run before deploying bootnodes:
#
# 1. Generate keys:
#    subkey generate-node-key --file boot0.key
#    subkey generate-node-key --file boot1.key
#
# 2. Base64 encode and update this manifest:
#    sed -i "s/boot0.key: \"\"/boot0.key: $(base64 -w 0 boot0.key)/" bootnode-static-keys-secret.yaml
#    sed -i "s/boot1.key: \"\"/boot1.key: $(base64 -w 0 boot1.key)/" bootnode-static-keys-secret.yaml
#
# 3. Apply the secret:
#    kubectl apply -f bootnode-static-keys-secret.yaml 